# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robArm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ETC_UI_main(object):
    def setupUi(self, ETC_UI_main):
        ETC_UI_main.setObjectName("ETC_UI_main")
        ETC_UI_main.resize(1534, 1004)
        self.centralwidget = QtWidgets.QWidget(ETC_UI_main)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 30, 1401, 921))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius: 100px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cFram_1 = QtWidgets.QFrame(self.frame)
        self.cFram_1.setGeometry(QtCore.QRect(0, 100, 331, 881))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cFram_1.sizePolicy().hasHeightForWidth())
        self.cFram_1.setSizePolicy(sizePolicy)
        self.cFram_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cFram_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cFram_1.setObjectName("cFram_1")
        self.line = QtWidgets.QFrame(self.cFram_1)
        self.line.setGeometry(QtCore.QRect(309, -140, 21, 1111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 164, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 164, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 164, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line.setPalette(palette)
        self.line.setFocusPolicy(QtCore.Qt.TabFocus)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_4 = QtWidgets.QFrame(self.cFram_1)
        self.frame_4.setGeometry(QtCore.QRect(60, 540, 216, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(120, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(16777214, 16777215))
        palette = QtGui.QPalette()
        self.frame_4.setPalette(palette)
        self.frame_4.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(153, 153, 153);\n"
"    \n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gjz_button = QtWidgets.QPushButton(self.frame_7)
        self.gjz_button.setGeometry(QtCore.QRect(130, 10, 81, 80))
        self.gjz_button.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gjz_button.setFont(font)
        self.gjz_button.setFlat(False)
        self.gjz_button.setObjectName("gjz_button")
        self.gjz_line = QtWidgets.QLineEdit(self.frame_7)
        self.gjz_line.setGeometry(QtCore.QRect(0, 30, 113, 41))
        self.gjz_line.setObjectName("gjz_line")
        self.verticalLayout.addWidget(self.frame_7)
        self.button_testFrame = QtWidgets.QPushButton(self.frame_4)
        self.button_testFrame.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_testFrame.setFont(font)
        self.button_testFrame.setFlat(False)
        self.button_testFrame.setObjectName("button_testFrame")
        self.verticalLayout.addWidget(self.button_testFrame)
        self.button_run = QtWidgets.QPushButton(self.frame_4)
        self.button_run.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_run.setFont(font)
        self.button_run.setObjectName("button_run")
        self.verticalLayout.addWidget(self.button_run)
        self.frame_6 = QtWidgets.QFrame(self.cFram_1)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 301, 531))
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"    border-top-left-radius: 40px;\n"
"    border-top-right-radius: 40px;\n"
"    border-bottom-left-radius: 40px;\n"
"    border-bottom-right-radius: 40px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.showTable = QtWidgets.QTextBrowser(self.frame_6)
        self.showTable.setGeometry(QtCore.QRect(10, 70, 281, 421))
        self.showTable.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.showTable.setObjectName("showTable")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(90, 10, 201, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(20, 20))
        self.label_6.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(28)
        self.label_6.setFont(font)
        self.label_6.setMouseTracking(True)
        self.label_6.setTabletTracking(False)
        self.label_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_6.setToolTipDuration(0)
        self.label_6.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_6.setIndent(-4)
        self.label_6.setObjectName("label_6")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(330, 110, 1081, 811))
        palette = QtGui.QPalette()
        self.frame_2.setPalette(palette)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 871, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(20, 20))
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setTabletTracking(False)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setToolTipDuration(0)
        self.label_2.setIndent(-4)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(880, 120, 191, 91))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(140, 190, 81, 51))
        self.label_4.setObjectName("label_4")
        self.recordButton = QtWidgets.QPushButton(self.frame_2)
        self.recordButton.setGeometry(QtCore.QRect(550, 660, 311, 121))
        self.recordButton.setStyleSheet("QPushButton{\n"
"    font-size:50px;\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(153, 153, 153);\n"
"    \n"
"}")
        self.recordButton.setObjectName("recordButton")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(130, 630, 111, 51))
        self.label_5.setObjectName("label_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(80, 690, 211, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(60, 250, 981, 381))
        self.frame_5.setStyleSheet("background-color: rgba(101, 102, 153, 59);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.slider_6 = QtWidgets.QSlider(self.frame_5)
        self.slider_6.setGeometry(QtCore.QRect(240, 330, 731, 41))
        self.slider_6.setMaximum(270)
        self.slider_6.setProperty("value", 157)
        self.slider_6.setSliderPosition(157)
        self.slider_6.setOrientation(QtCore.Qt.Horizontal)
        self.slider_6.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_6.setObjectName("slider_6")
        self.slider_3 = QtWidgets.QSlider(self.frame_5)
        self.slider_3.setGeometry(QtCore.QRect(240, 150, 731, 41))
        self.slider_3.setMaximum(270)
        self.slider_3.setProperty("value", 106)
        self.slider_3.setSliderPosition(106)
        self.slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_3.setObjectName("slider_3")
        self.slider_5 = QtWidgets.QSlider(self.frame_5)
        self.slider_5.setGeometry(QtCore.QRect(240, 270, 731, 41))
        self.slider_5.setMaximum(270)
        self.slider_5.setProperty("value", 100)
        self.slider_5.setSliderPosition(100)
        self.slider_5.setOrientation(QtCore.Qt.Horizontal)
        self.slider_5.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_5.setObjectName("slider_5")
        self.slider_2 = QtWidgets.QSlider(self.frame_5)
        self.slider_2.setGeometry(QtCore.QRect(240, 90, 731, 41))
        self.slider_2.setMaximum(270)
        self.slider_2.setSingleStep(1)
        self.slider_2.setProperty("value", 104)
        self.slider_2.setSliderPosition(104)
        self.slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_2.setObjectName("slider_2")
        self.slider_4 = QtWidgets.QSlider(self.frame_5)
        self.slider_4.setGeometry(QtCore.QRect(240, 210, 731, 41))
        self.slider_4.setMaximum(270)
        self.slider_4.setProperty("value", 166)
        self.slider_4.setSliderPosition(166)
        self.slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_4.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_4.setObjectName("slider_4")
        self.slider = QtWidgets.QSlider(self.frame_5)
        self.slider.setGeometry(QtCore.QRect(240, 30, 731, 41))
        self.slider.setMaximum(270)
        self.slider.setSingleStep(1)
        self.slider.setPageStep(10)
        self.slider.setProperty("value", 34)
        self.slider.setSliderPosition(34)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider.setObjectName("slider")
        self.textSlider = QtWidgets.QTextBrowser(self.frame_5)
        self.textSlider.setGeometry(QtCore.QRect(30, 20, 171, 41))
        self.textSlider.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.textSlider.setObjectName("textSlider")
        self.textSlider_2 = QtWidgets.QTextBrowser(self.frame_5)
        self.textSlider_2.setGeometry(QtCore.QRect(30, 80, 171, 41))
        self.textSlider_2.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.textSlider_2.setObjectName("textSlider_2")
        self.textSlider_3 = QtWidgets.QTextBrowser(self.frame_5)
        self.textSlider_3.setGeometry(QtCore.QRect(30, 140, 171, 41))
        self.textSlider_3.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.textSlider_3.setObjectName("textSlider_3")
        self.textSlider_4 = QtWidgets.QTextBrowser(self.frame_5)
        self.textSlider_4.setGeometry(QtCore.QRect(30, 200, 171, 41))
        self.textSlider_4.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.textSlider_4.setObjectName("textSlider_4")
        self.textSlider_5 = QtWidgets.QTextBrowser(self.frame_5)
        self.textSlider_5.setGeometry(QtCore.QRect(30, 260, 171, 41))
        self.textSlider_5.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.textSlider_5.setObjectName("textSlider_5")
        self.textSlider_6 = QtWidgets.QTextBrowser(self.frame_5)
        self.textSlider_6.setGeometry(QtCore.QRect(30, 320, 171, 41))
        self.textSlider_6.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.textSlider_6.setObjectName("textSlider_6")
        self.recordButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.recordButton_2.setGeometry(QtCore.QRect(70, 740, 231, 71))
        self.recordButton_2.setStyleSheet("QPushButton{\n"
"    font-size:30px;\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(153, 153, 153);\n"
"    \n"
"}")
        self.recordButton_2.setObjectName("recordButton_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, -10, 1401, 111))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-top-left-radius: 100px;\n"
"    border-top-right-radius: 100px;\n"
"    background-color:rgb(50, 50, 50);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.button_small = QtWidgets.QPushButton(self.frame_3)
        self.button_small.setGeometry(QtCore.QRect(1220, 50, 41, 34))
        self.button_small.setStyleSheet("border:none;\n"
"padding-bottom:5px;")
        self.button_small.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/image/green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_small.setIcon(icon)
        self.button_small.setObjectName("button_small")
        self.button_close = QtWidgets.QPushButton(self.frame_3)
        self.button_close.setGeometry(QtCore.QRect(1281, 50, 51, 34))
        self.button_close.setStyleSheet("border:none;\n"
"padding-bottom:5px;")
        self.button_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/image/red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon1)
        self.button_close.setObjectName("button_close")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(490, 50, 641, 41))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(-50, 90, 1471, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line_3.setPalette(palette)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frame_3.raise_()
        self.cFram_1.raise_()
        self.frame_2.raise_()
        self.line_3.raise_()
        ETC_UI_main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ETC_UI_main)
        self.statusbar.setObjectName("statusbar")
        ETC_UI_main.setStatusBar(self.statusbar)

        self.retranslateUi(ETC_UI_main)
        QtCore.QMetaObject.connectSlotsByName(ETC_UI_main)

    def retranslateUi(self, ETC_UI_main):
        _translate = QtCore.QCoreApplication.translate
        ETC_UI_main.setWindowTitle(_translate("ETC_UI_main", "MainWindow"))
        self.gjz_button.setText(_translate("ETC_UI_main", "测"))
        self.button_testFrame.setText(_translate("ETC_UI_main", "关键帧测试"))
        self.button_run.setText(_translate("ETC_UI_main", "启动"))
        self.label_6.setWhatsThis(_translate("ETC_UI_main", "<html><head/><body><p>智能防疫系统 Demo</p></body></html>"))
        self.label_6.setText(_translate("ETC_UI_main", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffeded;\">接收区</span></p></body></html>"))
        self.label_2.setWhatsThis(_translate("ETC_UI_main", "<html><head/><body><p>智能防疫系统 Demo</p></body></html>"))
        self.label_2.setText(_translate("ETC_UI_main", "<html><head/><body><p><span style=\" font-size:72pt; color:#ffeded;\">机械臂调试条</span></p></body></html>"))
        self.label_3.setText(_translate("ETC_UI_main", "<html><head/><body><p><span style=\" font-size:26pt; color:#ff7575;\">Ver.1.71</span></p></body></html>"))
        self.label_4.setText(_translate("ETC_UI_main", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffeded;\">数值</span></p></body></html>"))
        self.recordButton.setText(_translate("ETC_UI_main", "记录当前帧"))
        self.label_5.setText(_translate("ETC_UI_main", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffeded;\">串口名</span></p></body></html>"))
        self.textSlider.setHtml(_translate("ETC_UI_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.recordButton_2.setText(_translate("ETC_UI_main", "开关串口"))
        self.label.setText(_translate("ETC_UI_main", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">@工巡赛·机械臂调试软件（ V1.71 ）</span></p></body></html>"))
import res_rc
